services:
  - type: web
    name: pdf-saas-app
    env: python
    buildCommand: |
      apt-get update && apt-get install -y \
        libreoffice \
        calibre \
        poppler-utils \
        tesseract-ocr \
        python3-pip \
        python3-venv
      rm -rf alembic/versions/*.py
      pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AZURE_STORAGE_CONNECTION_STRING
        sync: false 