services:
  - type: web
    name: pdf-saas-app
    env: python
    buildCommand: |
      apt-get update
      apt-get install -y --no-install-recommends curl tesseract-ocr poppler-utils libreoffice libgl1-mesa-glx libglib2.0-0 libxrender1 libsm6 libxext6 python3-pip python3-venv
      pip install -r requirements.txt
    startCommand: python migrate_and_start.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AZURE_STORAGE_CONNECTION_STRING
        sync: false
      - key: REDIS_URL
        sync: false

  - type: redis
    name: pdf-saas-redis
    ipAllowList: []
    plan: free 